# Generated by Django 3.0.2 on 2020-02-06 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_key


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.BooleanField(blank=True, default=False, null=True)),
                ('donor', models.BooleanField(default=False)),
                ('last_active', models.IntegerField(blank=True, default=0, null=True)),
                ('listen_key', models.TextField(blank=True, default=utils.generate_key.generate_key, null=True)),
                ('losing_requests', models.IntegerField(blank=True, default=0, null=True)),
                ('losing_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('requests_paused', models.BooleanField(blank=True, default=False, null=True)),
                ('total_mind_changes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('total_requests', models.IntegerField(blank=True, default=0, null=True)),
                ('total_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('winning_requests', models.IntegerField(blank=True, default=0, null=True)),
                ('winning_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_to_station_ends_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.CharField(max_length=128)),
                ('icecast_id', models.IntegerField()),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('lock_to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config.Station')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Relay')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Station')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=utils.generate_key.generate_key, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
