import AlbumWithDetail from "./types/albumWithDetail";
import AllSongsSong from "./types/allSongsSong";
import AllStationsInfo from "./types/allStationsInfo";
import ApiInfo from "./types/apiInfo";
import ArtistInLibrary from "./types/artistInLibrary";
import ArtistWithSongs from "./types/artistWithSongs";
import RainwaveError from "./types/error";
import RainwaveSDKErrorClear from "./types/errorClear";
import FaveSong from "./types/faveSong";
import MessageId from "./types/messageId";
import SongGroup from "./types/songGroup";
import User from "./types/user";

export interface RainwaveResponseTypes {
  album: AlbumWithDetail;
  all_albums_by_cursor: unknown;
  all_artists: ArtistInLibrary[];
  all_faves: FaveSong[];
  all_groups: SongGroup[];
  all_songs: AllSongsSong[];
  all_stations_info: AllStationsInfo[];
  already_voted: unknown;
  api_info: ApiInfo;
  artist: ArtistWithSongs;
  build_version: number;
  cookie_domain: string;
  delete_request_result: unknown;
  error_report_result: unknown;
  error: RainwaveError;
  fave_album_result: unknown;
  fave_all_songs_result: unknown;
  fave_song_result: unknown;
  group: unknown;
  listener: unknown;
  live_voting: unknown;
  locale: unknown;
  locales: unknown;
  message_id: MessageId;
  mobile: unknown;
  on_draw: unknown;
  on_init: unknown;
  on_measure: unknown;
  pause_request_queue_result: unknown;
  ping: undefined;
  playback_history: unknown;
  rate_result: unknown;
  redownload_m3u: unknown;
  relays: unknown;
  request_favorited_songs_result: unknown;
  request_line_result: unknown;
  request_line: unknown;
  request_result: unknown;
  request_unrated_songs_result: unknown;
  requests: unknown;
  sched_current: unknown;
  sched_history: unknown;
  sched_next: unknown;
  sdk_exception: Error;
  sdk_error_clear: RainwaveSDKErrorClear;
  sdk_schedule_synced: true;
  search_results: unknown;
  song: unknown;
  station_list: unknown;
  station_song_count: unknown;
  stations: unknown;
  stream_filename: unknown;
  sync_result: RainwaveError;
  top_100: unknown;
  unpause_request_queue_result: unknown;
  unrated_songs: unknown;
  user_info_result: unknown;
  user_recent_votes: unknown;
  user_requested_history: unknown;
  user: User;
  vote_result: unknown;
  websocket_host: unknown;
  wsok: true;
  wserror: RainwaveError;
}
