import User from "./types/user";

export interface ResponseTypes {
  album: unknown;
  all_albums_by_cursor: unknown;
  all_artists: unknown;
  all_faves: unknown;
  all_groups: unknown;
  all_songs: unknown;
  all_stations_info: unknown;
  already_voted: unknown;
  artist: unknown;
  build_version: unknown;
  cookie_domain: unknown;
  delete_request_result: unknown;
  error_report_result: unknown;
  error: unknown;
  fave_album_result: unknown;
  fave_all_songs_result: unknown;
  fave_song_result: unknown;
  group: unknown;
  listener: unknown;
  live_voting: unknown;
  locale: unknown;
  locales: unknown;
  mobile: unknown;
  on_draw: unknown;
  on_init: unknown;
  on_measure: unknown;
  pause_request_queue_result: unknown;
  playback_history: unknown;
  rate_result: unknown;
  redownload_m3u: unknown;
  relays: unknown;
  request_favorited_songs_result: unknown;
  request_line_result: unknown;
  request_line: unknown;
  request_result: unknown;
  request_unrated_songs_result: unknown;
  requests: unknown;
  sched_current: unknown;
  sched_history: unknown;
  sched_next: unknown;
  search_results: unknown;
  song: unknown;
  station_list: unknown;
  station_song_count: unknown;
  stations: unknown;
  stream_filename: unknown;
  top_100: unknown;
  unpause_request_queue_result: unknown;
  unrated_songs: unknown;
  user_info_result: unknown;
  user_recent_votes: unknown;
  user_requested_history: unknown;
  user: User;
  vote_result: unknown;
  websocket_host: unknown;
}

export interface InfoResponse {
  all_stations_info: ResponseTypes["all_stations_info"];
  already_voted?: ResponseTypes["already_voted"];
  live_voting?: ResponseTypes["live_voting"];
  request_line?: ResponseTypes["request_line"];
  requests?: ResponseTypes["requests"];
  sched_current: ResponseTypes["sched_current"];
  sched_history: ResponseTypes["sched_history"];
  sched_next: ResponseTypes["sched_next"];
  user: ResponseTypes["user"];
}
