# Generated by Django 3.0.2 on 2020-05-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200523_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='subdirectory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
