# Generated by Django 3.0.2 on 2020-02-05 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.SmallIntegerField(choices=[(0, 'Conflict'), (1, 'Warning'), (2, 'Normal'), (3, 'Queue'), (4, 'Request')], default=2)),
                ('position', models.SmallIntegerField()),
                ('votes', models.SmallIntegerField(default=0)),
                ('song_on_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.SongOnStation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event')),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('election_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.ElectionEntry')),
                ('song_on_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.SongOnStation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLinePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_start', models.IntegerField(blank=True, null=True)),
                ('expires_if_not_tuned_in_at', models.DateTimeField(blank=True, null=True)),
                ('expires_if_no_valid_song_at', models.DateTimeField(blank=True, null=True)),
                ('has_had_valid_song', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0)),
                ('song_on_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.SongOnStation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('use_crossfade', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_set', to=settings.AUTH_USER_MODEL)),
                ('dj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_event_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('song_on_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.SongOnStation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FulfilledRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled_at', models.DateTimeField(auto_now_add=True)),
                ('wait_time_for_fulfillment', models.IntegerField()),
                ('line_size_at_fulfillment', models.IntegerField()),
                ('song_on_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.SongOnStation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Producer'),
        ),
        migrations.AddField(
            model_name='event',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Station'),
        ),
        migrations.AddField(
            model_name='electionentry',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Election'),
        ),
    ]
